# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBApplyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_username', models.CharField(default='oracle', max_length=20)),
                ('os_passwd', models.CharField(default='oracle123', max_length=20)),
                ('os_ip_addr', models.CharField(max_length=15)),
                ('ora_home', models.CharField(default='/u01/app/oracle/product/11.2.0/dbhome_1', max_length=100)),
                ('ora_sid', models.CharField(max_length=8)),
                ('ora_passwd', models.CharField(default='oracle123', max_length=20)),
                ('ora_charset', models.CharField(max_length=15)),
                ('ora_ncharset', models.CharField(max_length=15)),
                ('ora_sga', models.PositiveSmallIntegerField()),
                ('ora_pga', models.PositiveSmallIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
