# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbapplyinfo',
            name='ora_pga',
            field=models.PositiveSmallIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='dbapplyinfo',
            name='ora_sga',
            field=models.PositiveSmallIntegerField(max_length=4),
        ),
    ]
