# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodb', '0003_auto_20170707_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbapplyinfo',
            name='ora_pga',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='dbapplyinfo',
            name='ora_sga',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
